export const repositoriesConfig = [
    {
        stars: 5,
        title: 'Repository Title',
        description: "Lorem Ipsum is s",
        tags: ['javascript', 'dogs', 'animals', '+'],
        issues: 67,
        lastUpdated: '39min',
    },
    {
        stars: 5,
        title: '',
        description: "",
        tags: [],
        issues: 1,
        lastUpdated: '',
    },
    {
        stars: 5,
        title: 'Repository Title',
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to ....",
        tags: ['javascript', 'dogs', 'animals', '+'],
        issues: 67,
        lastUpdated: '39min',
    },
    {
        stars: 5,
        title: 'Repository Title',
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to ....",
        tags: ['javascript', 'dogs', 'animals', '+'],
        issues: 67,
        lastUpdated: '39min',
    },
    {
        stars: 5,
        title: 'Repository Title',
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to ....",
        tags: ['javascript', 'dogs', 'animals', '+'],
        issues: 67,
        lastUpdated: '39min',
    },
    {
        stars: 5,
        title: 'Repository Title',
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to ....",
        tags: ['javascript', 'dogs', 'animals', '+'],
        issues: 67,
        lastUpdated: '39min',
    },
    {
        stars: 5,
        title: 'Repository Title',
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to ....",
        tags: ['javascript', 'php', 'dogs', 'animals', '+'],
        issues: 67,
        lastUpdated: '39min',
    },
    {
        stars: 5,
        title: 'Repository Title',
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to ....",
        tags: ['javascript', 'php', 'dogs', 'animals', '+'],
        issues: 67,
        lastUpdated: '39min',
    },
    {
        stars: 5,
        title: 'Repository Title',
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to ....",
        tags: ['javascript', 'php', 'dogs', 'animals', '+'],
        issues: 67,
        lastUpdated: '39min',
    },
    {
        stars: 5,
        title: 'Repository Title',
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to ....",
        tags: ['javascript', 'php', 'dogs', 'animals', '+'],
        issues: 67,
        lastUpdated: '39min',
    },
    {
        stars: 5,
        title: 'Repository Title',
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to ....",
        tags: ['javascript', 'php', 'dogs', 'animals', '+'],
        issues: 67,
        lastUpdated: '39min',
    },
    {
        stars: 5,
        title: 'Repository Title',
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to ....",
        tags: ['javascript', 'php', 'dogs', 'animals', '+'],
        issues: 67,
        lastUpdated: '39min',
    }
];